### ISSUE TITLE
chm搜索不好用

### ISSUE THREAD

**Issue by luosq0123** [myfreeer/cppreference2mshelp#14]
索引里有的东西搜不出来。
比如iterator里的prev，next，但是可以手动找到，搜advance，往下数十几个就是prev，next

**Comment by lywyue** [comment]
搜索make只有一个make_heap

**Comment by myfreeer** [comment]
索引没有排序

**Comment by myfreeer** [comment]
排序了索引的chm:
[cppreference-zh-20200816-dev.zip](https://github.com/myfreeer/cppreference2mshelp/files/5744480/cppreference-zh-20200816-dev.zip)

**Comment by luosq0123** [comment]
> 排序了索引的chm:
> [cppreference-zh-20200816-dev.zip](https://github.com/myfreeer/cppreference2mshelp/files/5744480/cppreference-zh-20200816-dev.zip)

十分感谢，建议下次release里同时提供排好序的版本
