### ISSUE TITLE
在html中怎么搜索？

### ISSUE THREAD

**Issue by QH-Liang** [myfreeer/cppreference2mshelp#17]
HTML文档没法搜索，没有搜索框

**Comment by myfreeer** [comment]
使用快捷键 `Ctrl+F` 进行页面内搜索

**Comment by whousemyname** [comment]
为什么我下载下来我的文档什么都没有显示，是因为代理的原因吗

**Comment by myfreeer** [comment]
@whousemyname 文件上右键属性-解除锁定试试
另外，此话题与本 issue 无关
