### ISSUE TITLE
https://zh.cppreference.com/w/cpp/utility/variant/operator=  对应chm的离线页面没有

### ISSUE THREAD

**Issue by qwertlooker** [myfreeer/cppreference2mshelp#18]
![image](https://user-images.githubusercontent.com/1764593/114482635-78e0cf00-9c39-11eb-8bce-ba865d80f611.png)

**Comment by myfreeer** [comment]
![image](https://user-images.githubusercontent.com/17702502/114549102-2e8c3c00-9c93-11eb-9e15-aefd0f60c4dc.png)
是这个页面吗？通过什么方式进入的？
图为cppreference-zh-20210212.chm

**Comment by myfreeer** [comment]
![image](https://user-images.githubusercontent.com/17702502/114549707-ede0f280-9c93-11eb-8b1b-59e6af816976.png)
可能是url转义问题

**Comment by myfreeer** [comment]
https://github.com/myfreeer/cppreference2mshelp/blob/8c1f25a95ec497c90b5103e2856f2a1b418f2abe/make_chm.php#L54

此处使用 `$relativename`

https://github.com/myfreeer/cppreference2mshelp/blob/8c1f25a95ec497c90b5103e2856f2a1b418f2abe/make_chm.php#L164

此处使用 `urlencode($new_value)`

url转义处理可能需统一

**Comment by qwertlooker** [comment]
是这个页面。
出错页面的地址：
res://ieframe.dll/dnserrordiagoff.htm#mk:@MSITStore:X:\tool\cppreference-zh-20210212.chm::/chmhelp/cpp-utility-variant-operator_3D.html

我的环境：
![image](https://user-images.githubusercontent.com/1764593/114643426-33d79e00-9d08-11eb-8c74-a46993e27969.png)

**Comment by myfreeer** [comment]
https://github.com/myfreeer/cppreference2mshelp/releases/tag/2021.02.1
