### ISSUE TITLE
代码显示宽度问题

### ISSUE THREAD

**Issue by muyanchen-zen** [myfreeer/cppreference2mshelp#19]
![image](https://user-images.githubusercontent.com/47655810/124436295-642f5580-dda8-11eb-8e64-8effc16569b0.png)

代码显示宽度很小看着很难受

**Comment by myfreeer** [comment]
下一版改为内容适应窗体宽度并缩小窗体默认宽度

hhp 文件格式
https://www-user.tu-chemnitz.de/~heha/hsn/chm/chmspec.chm/hhp.html

相关代码
https://github.com/myfreeer/cppreference2mshelp/blob/2abd81d13a0ef1f75c18918a95595eee4d866ca4/make_chm.php#L393
https://github.com/myfreeer/cppreference2mshelp/blob/2abd81d13a0ef1f75c18918a95595eee4d866ca4/css/ext.css#L1365
https://github.com/myfreeer/cppreference2mshelp/blob/2abd81d13a0ef1f75c18918a95595eee4d866ca4/css/site_modules.css#L1670-L1675

**Comment by myfreeer** [comment]
https://github.com/myfreeer/cppreference2mshelp/releases/tag/2021.12

**Comment by muyanchen-zen** [comment]
> 

像是被body的宽度值限制了
