### ISSUE TITLE
生成的chm没有Back按钮，非常不方便

### ISSUE THREAD

**Issue by MKcKr0** [myfreeer/cppreference2mshelp#2]
[https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/adding-buttons-to-a-help-window](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/adding-buttons-to-a-help-window)

**Comment by myfreeer** [comment]
可以使用`Baskspace`键后退
