### ISSUE TITLE
有没有可能提供docset格式的文件，Mac下使用Dash看文档不是很方便

### ISSUE THREAD

**Issue by 0x11901** [myfreeer/cppreference2mshelp#3]
RT

**Comment by myfreeer** [comment]
下载`html-book-*.7z` （处理完成的 HTML 文档），然后用官方提供的工具转换格式

>https://kapeli.com/docsets#dashDocset

> Docsets are essentially just a folder containing the HTML documentation and a SQLite database that indexes the files.
If the HTML docs you want to index are well-formatted, it might be easier to generate the docset using [Dashing](https://github.com/technosophos/dashing#readme) instead of writing your own generation script.

**Comment by 0x11901** [comment]
十分感谢🙏！
