### ISSUE TITLE
feat: 能否支持生成 docset, 这样macOS的dash.app和Windows的zeal都可以用

### ISSUE THREAD

**Issue by epheien** [myfreeer/cppreference2mshelp#30]

**Comment by myfreeer** [comment]
Duplicate of #3 
可以参照 https://github.com/myfreeer/cppreference2mshelp/issues/3#issuecomment-439379698

**Comment by epheien** [comment]
> Duplicate of #3 可以参照 [#3 (comment)](https://github.com/myfreeer/cppreference2mshelp/issues/3#issuecomment-439379698)

看起来可以, 就是会缺少一些 package 索引内容
