### ISSUE TITLE
请问在有办法在成员函数上F1也能跳转文档吗，像qt内置文档那样

### ISSUE THREAD

**Issue by stephenxin** [myfreeer/cppreference2mshelp#6]
`
std::string test;
  test.clear();
`
比如，在clear上f1，出来的选择窗口是没有string的，像是没找到，只能在std::string上f1才有效，感谢！

**Comment by myfreeer** [comment]
询问上游 ([p12tic/cppreference-doc](https://github.com/p12tic/cppreference-doc)或[PeterFeicht/cppreference-doc](https://github.com/PeterFeicht/cppreference-doc)) 关于 Qt 文档相关问题，本版本未修改相关逻辑。

**Comment by stephenxin** [comment]
好的，谢谢
