### ISSUE TITLE
图片显示异常

### ISSUE THREAD

**Issue by MagicConchCpp** [myfreeer/cppreference2mshelp#9]
我使用的是cppreference-zh-20191207.chm

当我 打开**输入/输出库**，这个继承图显示不出来。
![image](https://user-images.githubusercontent.com/30330993/73418496-b28c2980-4356-11ea-84b8-b0f7daad0e4e.png)

**Comment by myfreeer** [comment]
![image](https://user-images.githubusercontent.com/17702502/73539476-6c26ef80-4468-11ea-85bd-3c580bfb10d4.png)

你可能在使用早期版本的IE，Win10+IE11正常

**Comment by liutumor** [comment]
使用chm的时候在索引里面输入关键字查找的时候，找到的主题是一行行都是无标题怎么解决。
